GSP.server=localhost
GSP.server.port=49053
GSP.numberOfnodes=3
GSP.node0=localhost
GSP.node1=localhost
GSP.node2=localhost
GSP.rmiregistry.port=1099


GSP.writePercent=30
GSP.operations.per.batch=50
GSP.data.directory=data/
GSP.serviceName=GraphEngine
GSP.graph.file=data/intial_graph.txt
GSP.server.log.directory=log/
GSP.client.log.directory=log/
GSP.server.verbose=true
GSP.client.verbose=true
GSP.batchMode=true
GSP.precomputeMode=false
GSP.client.maxOpDelayMs=0
GSP.client.maxInterRequestSleepMs=0