GSP.server=localhost
GSP.server.port=49053
GSP.rmiregistry.port=1099
GSP.serviceName=GraphEngine
GSP.graph.file=data/intial_graph.txt
GSP.data.directory=data/
GSP.server.log.directory=log/
GSP.client.log.directory=log/
GSP.server.verbose=true
GSP.client.verbose=true
GSP.batchMode=true
GSP.operations.per.batch=50
GSP.client.timeout.seconds=120
GSP.server.operations.sleep=0
GSP.client.operations.sleep=0
GSP.precomputeMode=true
GSP.writePercent=30
GSP.numberOfnodes=20
GSP.node0=localhost
GSP.node1=localhost
GSP.node2=localhost
GSP.node3=localhost
GSP.node4=localhost
GSP.node5=localhost
GSP.node6=localhost
GSP.node7=localhost
GSP.node8=localhost
GSP.node9=localhost
GSP.node10=localhost
GSP.node11=localhost
GSP.node12=localhost
GSP.node13=localhost
GSP.node14=localhost
GSP.node15=localhost
GSP.node16=localhost
GSP.node17=localhost
GSP.node18=localhost
GSP.node19=localhost
